version: '3.9'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ".:/app"
    command: flask run
      
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: course-qa
